### ISSUE TITLE
Strange GraphQL Configuration Error for a fully working and valid GraphQL schema

### ISSUE THREAD

**Issue by soulwife** [kaakaww/vuln-graphql-api#1]
Hello! First of all, thank you for a great promising product! It's really helpful to have a possibility to scan GraphQL queries as well. But, I am afraid, it's by some reason is not working in my case. I have a valid GraphQL schema (works safe and sound in production), but the tool tells me otherwise:

It's somehow misunderstands interfaces with objects:
![screen](http://i.imgur.com/IKL16ed.png)

**Comment by sgerlach** [comment]
Hi @soulwife! Thanks for getting a hold of us. I'm going to have our support person reach out to you and close this issue since it's not really related to this project. You should have a message from our support team shortly
